from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Mapping


def render_map_markdown(data: Mapping[str, Any]) -> str:
    repo = data.get("repo", {})
    orientation = data.get("orientation", {})
    lines = [
        f"# Skyhook — {repo.get('name', 'repository')}",
        "",
        "<!-- GENERATED by skyhook; edit source/config, then rerun skyhook init. -->",
        "",
        "## Start Here",
        "",
        orientation.get("summary", "").strip() or "No summary available.",
        "",
    ]
    start_here = orientation.get("agentStartHere", []) or []
    if start_here:
        lines.append("Read these first:")
        lines.append("")
        for item in start_here:
            lines.append(f"- `{item}`")
        lines.append("")

    lines.extend(["## Major Code Areas", ""])
    for area in data.get("codeAreas", []) or []:
        lines.append(f"### {area.get('name', area.get('id', 'Area'))}")
        purpose = area.get("purpose", "")
        if purpose:
            lines.append(purpose)
            lines.append("")
        _list_field(lines, "Paths", area.get("paths", []))
        _list_field(lines, "Entrypoints", area.get("entrypoints", []))
        _list_field(lines, "Related docs", area.get("relatedDocs", []))
        _list_field(lines, "Relevant tests", area.get("relevantTests", []))
        _list_field(lines, "Verification", area.get("verificationCommands", []))
        confidence = area.get("confidence")
        if confidence:
            lines.append(f"Confidence: `{confidence}`")
            lines.append("")

    lines.extend(["## Important Documentation", ""])
    for doc in data.get("docs", []) or []:
        title = doc.get("title") or doc.get("path")
        lines.append(f"- `{doc.get('path')}` — **{title}**")
        summary = doc.get("summary")
        if summary:
            lines.append(f"  {summary}")
        when = doc.get("whenToRead")
        if when:
            lines.append(f"  Read when: {when}")
    lines.append("")

    lines.extend(["## Architecture And Design", ""])
    architecture = data.get("architecture", []) or []
    if not architecture:
        lines.append("No architecture or design documents were identified.")
        lines.append("")
    for arch in architecture:
        lines.append(f"- **{arch.get('name', 'Architecture')}** (`{arch.get('kind', 'other')}`): {', '.join('`' + p + '`' for p in arch.get('paths', []))}")
        if arch.get("summary"):
            lines.append(f"  {arch['summary']}")
    lines.append("")

    lines.extend(["## Known Gotchas", ""])
    gotchas = orientation.get("knownGotchas", []) or []
    if gotchas:
        for gotcha in gotchas:
            lines.append(f"- {gotcha}")
    else:
        lines.append("- None recorded.")
    lines.append("")

    lines.extend(["## Generated Symbol Hints", ""])
    symbols = data.get("symbols", []) or []
    if symbols:
        lines.append("| Name | Kind | Path | Area |")
        lines.append("|---|---|---|---|")
        for symbol in symbols[:200]:
            lines.append(
                f"| `{symbol.get('name', '')}` | {symbol.get('kind', '')} | `{symbol.get('path', '')}` | `{symbol.get('areaId', '')}` |"
            )
    else:
        lines.append("No symbol hints generated.")
    lines.append("")
    return "\n".join(lines)


def render_index_markdown(data: Mapping[str, Any]) -> str:
    repo = data.get("repo", {})
    orientation = data.get("orientation", {})
    lines = [
        f"# Skyhook Index — {repo.get('name', 'repository')}",
        "",
        "<!-- GENERATED by skyhook. Compact entrypoint for coding agents. -->",
        "",
        "## Start Here",
        "",
        orientation.get("summary", "").strip() or "No summary available.",
        "",
    ]
    for item in orientation.get("agentStartHere", []) or []:
        lines.append(f"- `{item}`")
    lines.append("")

    lines.extend(["## Code Areas", ""])
    areas = data.get("codeAreas", []) or []
    if areas:
        lines.append("| Area | Paths | Tests | Page |")
        lines.append("|---|---|---|---|")
        for area in areas:
            area_id = str(area.get("id") or area.get("name") or "area")
            paths = ", ".join(f"`{path}`" for path in (area.get("paths", []) or [])[:3])
            tests = len(area.get("relevantTests", []) or [])
            lines.append(f"| {area.get('name') or area_id} | {paths} | {tests} | `.skyhook/areas/{_slug(area_id)}.md` |")
    else:
        lines.append("No code areas detected.")
    lines.append("")

    lines.extend(["## Architecture", ""])
    for item in (data.get("architecture", []) or [])[:8]:
        paths = ", ".join(f"`{path}`" for path in item.get("paths", []) or [])
        lines.append(f"- {item.get('name', 'Architecture')} ({item.get('kind', 'other')}): {paths}")
    if not data.get("architecture"):
        lines.append("- No architecture or design documents detected.")
    lines.append("")

    lines.extend(["## Generated Files", ""])
    lines.append("- `.skyhook/map.md`: full generated map")
    lines.append("- `.skyhook/docs.md`: documentation inventory")
    lines.append("- `.skyhook/architecture.md`: architecture and design references")
    lines.append("- `.skyhook/tests.md`: test discovery and verification hints")
    lines.append("- `.skyhook/areas/<area>.md`: focused subsystem pages")
    lines.append("")
    return "\n".join(lines)


def render_area_markdown(data: Mapping[str, Any], area: Mapping[str, Any]) -> str:
    area_id = str(area.get("id") or area.get("name") or "area")
    lines = [
        f"# Skyhook Area — {area.get('name') or area_id}",
        "",
        "<!-- GENERATED by skyhook. Focused context for one code area. -->",
        "",
    ]
    if area.get("purpose"):
        lines.extend(["## Purpose", "", str(area["purpose"]), ""])
    _list_field(lines, "Paths", area.get("paths", []))
    _list_field(lines, "Responsibilities", area.get("responsibilities", []))
    _list_field(lines, "Entrypoints", area.get("entrypoints", []))
    _list_field(lines, "Public contracts", area.get("publicContracts", []))
    _list_field(lines, "Dependencies", area.get("dependencies", []))
    _list_field(lines, "Related docs", area.get("relatedDocs", []))
    _list_field(lines, "Relevant tests", area.get("relevantTests", []))
    _list_field(lines, "Verification commands", area.get("verificationCommands", []))
    _list_field(lines, "Change rules", area.get("changeRules", []))
    _list_field(lines, "Danger zones", area.get("dangerZones", []))

    symbols = [symbol for symbol in data.get("symbols", []) or [] if symbol.get("areaId") == area_id]
    lines.extend(["## Symbol Hints", ""])
    if symbols:
        lines.append("| Name | Kind | Path |")
        lines.append("|---|---|---|")
        for symbol in symbols[:80]:
            lines.append(f"| `{symbol.get('name', '')}` | {symbol.get('kind', '')} | `{symbol.get('path', '')}` |")
    else:
        lines.append("No symbol hints generated for this area.")
    lines.append("")
    return "\n".join(lines)


def render_docs_markdown(data: Mapping[str, Any]) -> str:
    lines = [
        f"# Skyhook Docs — {data.get('repo', {}).get('name', 'repository')}",
        "",
        "<!-- GENERATED by skyhook. -->",
        "",
    ]
    for doc in data.get("docs", []) or []:
        lines.append(f"## {doc.get('title') or doc.get('path')}")
        lines.append("")
        lines.append(f"- Path: `{doc.get('path')}`")
        lines.append(f"- Kind: `{doc.get('kind', 'unknown')}`")
        if doc.get("summary"):
            lines.append(f"- Summary: {doc['summary']}")
        if doc.get("whenToRead"):
            lines.append(f"- When to read: {doc['whenToRead']}")
        lines.append("")
    return "\n".join(lines)


def render_architecture_markdown(data: Mapping[str, Any]) -> str:
    lines = [
        f"# Skyhook Architecture — {data.get('repo', {}).get('name', 'repository')}",
        "",
        "<!-- GENERATED by skyhook. -->",
        "",
    ]
    items = data.get("architecture", []) or []
    if not items:
        lines.append("No architecture or design documents were identified.")
        lines.append("")
        return "\n".join(lines)
    for item in items:
        lines.append(f"## {item.get('name', 'Architecture')}")
        lines.append("")
        lines.append(f"- Kind: `{item.get('kind', 'other')}`")
        paths = item.get("paths", []) or []
        if paths:
            lines.append("- Paths:")
            for path in paths:
                lines.append(f"  - `{path}`")
        if item.get("summary"):
            lines.append(f"- Summary: {item['summary']}")
        lines.append("")
    return "\n".join(lines)


def render_tests_markdown(data: Mapping[str, Any]) -> str:
    lines = [
        f"# Skyhook Tests — {data.get('repo', {}).get('name', 'repository')}",
        "",
        "<!-- GENERATED by skyhook. -->",
        "",
    ]
    tests = data.get("tests", []) or []
    if tests:
        lines.append("| Path | Framework | Target hints |")
        lines.append("|---|---|---|")
        for test in tests[:300]:
            hints = ", ".join(f"`{hint}`" for hint in test.get("targetHints", []) or [])
            lines.append(f"| `{test.get('path', '')}` | {test.get('framework', 'unknown')} | {hints} |")
    else:
        lines.append("No test files were identified.")
    lines.append("")

    lines.extend(["## Area Verification", ""])
    for area in data.get("codeAreas", []) or []:
        commands = area.get("verificationCommands", []) or []
        relevant = area.get("relevantTests", []) or []
        if not commands and not relevant:
            continue
        lines.append(f"### {area.get('name') or area.get('id')}")
        _list_field(lines, "Commands", commands)
        _list_field(lines, "Relevant tests", relevant[:20])
    return "\n".join(lines)


def render_route_markdown(route: Mapping[str, Any]) -> str:
    lines = [
        "# Skyhook Route",
        "",
        "<!-- GENERATED by skyhook route. -->",
        "",
        "## Task",
        "",
        str(route.get("task", "")).strip(),
        "",
        f"Profile: `{route.get('profile', 'implementation')}`",
        "",
        f"Confidence: `{route.get('confidence', 'low')}`",
        "",
    ]
    assignment = route.get("assignment") or {}
    if assignment:
        lines.extend(
            [
                "## Assignment",
                "",
                f"- Team: `{assignment.get('team', '')}`",
                f"- Behavior: `{assignment.get('behavior', '')}`",
                f"- Route profile: `{assignment.get('routeProfile', route.get('profile', ''))}`",
            ]
        )
        if assignment.get("instructions"):
            lines.append(f"- Instructions: {assignment['instructions']}")
        lines.append("")
    _list_field(lines, "Profile Guidance", route.get("profileGuidance", []))
    _list_field(lines, "Read First", route.get("readFirst", []))
    _list_field(lines, "Likely Edit Targets", route.get("likelyEditTargets", []))
    _list_field(lines, "Relevant Tests", route.get("relevantTests", []))
    _list_field(lines, "Architecture And Design", route.get("architecture", []))
    _list_field(lines, "Constraints And Gotchas", route.get("constraints", []))
    _list_field(lines, "Search Terms", route.get("searchTerms", []))
    _render_call_graph(lines, route)
    evidence = route.get("evidence", []) or []
    lines.extend(["## Evidence", ""])
    if evidence:
        for item in evidence:
            path = item.get("path")
            label = f"`{path}`" if path else item.get("label", "evidence")
            lines.append(f"- {label}: {item.get('reason', '')}")
    else:
        lines.append("- No evidence generated.")
    lines.append("")
    return "\n".join(lines)


def _render_call_graph(lines: list, route: Mapping[str, Any]) -> None:
    """Gated AST call-graph section (omitted when the graph wasn't available)."""
    chains = route.get("callChains") or []
    blast = route.get("blastRadius")
    if not chains and not blast:
        return
    lines.extend(["## Call Graph", "", "_Approximate (AST name-resolution)._", ""])
    for cc in chains:
        callers = ", ".join(f"`{c['name']}`" for c in cc.get("callers", [])) or "—"
        callees = ", ".join(f"`{c['name']}`" for c in cc.get("callees", [])) or "—"
        lines.append(f"- `{cc['symbol']}` — called by: {callers}; calls: {callees}")
    if blast and blast.get("impactedFiles"):
        files = ", ".join(f"`{p}`" for p in blast["impactedFiles"])
        lines.append(f"- Blast radius of `{blast['target']}`: {files}")
    lines.append("")


def markdown_outputs(data: Mapping[str, Any]) -> Dict[str, str]:
    outputs = {
        "map.md": render_map_markdown(data),
        "INDEX.md": render_index_markdown(data),
        "docs.md": render_docs_markdown(data),
        "architecture.md": render_architecture_markdown(data),
        "tests.md": render_tests_markdown(data),
    }
    for area in data.get("codeAreas", []) or []:
        area_id = str(area.get("id") or area.get("name") or "area")
        outputs[f"areas/{_slug(area_id)}.md"] = render_area_markdown(data, area)
    return outputs


def write_markdown_outputs(output_dir: Path, data: Mapping[str, Any]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for rel_path, content in markdown_outputs(data).items():
        path = output_dir / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _list_field(lines: list[str], label: str, values: Any) -> None:
    if not values:
        return
    lines.append(f"{label}:")
    for value in values:
        lines.append(f"- `{value}`")
    lines.append("")


def _slug(value: str) -> str:
    slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug or "area"
